# Generated by Django 5.0.6 on 2024-07-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='mobileno',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
